[package]
name = "paulzyw02/digital-intelligence-hub"
version = "0.1.0"
description = "Paul Wang Digital Intelligence Hub"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
public = "dist"

[[command]]
name = "script"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
# This tells Wasmer to serve the 'dist' folder and fallback to index.html for React Router
env = ["SERVER_PORT=8080", "SERVER_ROOT=/public", "SERVER_FALLBACK_PAGE=/public/index.html"]
